# import = ["/home/john/.config/alacritty/alacritty-master/dracula.toml"]
import = ["/home/john/.config/alacritty/catppuccin-mocha.toml"]
# import = ["/home/john/.config/alacritty/arch-fill-colorscheme.toml"]

[cursor]
style = { shape = "Beam", blinking = "On" }

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular"}
size = 13

[window]
padding = { x = 15, y = 15}

[env]
TERM = "xterm-256color"
